service: salestack

provider:
    name: aws
    region: ap-northeast-1
    runtime: provided.al2
    stage: ${opt:stage, 'dev'}

plugins:
    - ./vendor/bref/bref

functions:
    report-api:
        handler: index.php
        description: ''
        runtime: php-82
        events:
            - httpApi:
                path: /reports
                method: post

resources:
    Resources:
        Storage:
            Type: AWS::S3::Bucket
            Properties:
                BucketName: ${self:service}-${self:provider.stage}-serverless

# Exclude files from deployment
package:
    patterns:
        - '!node_modules/**'
        - '!tests/**'
