service: salestack-reports

provider:
    name: aws
    region: ap-northeast-1
    runtime: provided.al2
    stage: ${opt:stage, 'dev'}

plugins:
    - ./vendor/bref/bref
    - serverless-s3-sync

functions:
    api:
        handler: index.php
        name: ${self:service}-api-${self:provider.stage}
        runtime: php-82
        events:
            - httpApi:
                path: /reports
                method: post

resources:
    Resources:
        Template:
            Type: AWS::S3::Bucket
            Properties:
                BucketName: ${self:service}-template-${self:provider.stage}

custom:
    s3Sync:
        - bucketName: ${self:service}-template-${self:provider.stage}
          localDir: template

# Exclude files from deployment
package:
    patterns:
        - '!node_modules/**'
        - '!tests/**'
