service: salestack

provider:
    name: aws
    region: ap-northeast-1
    runtime: provided.al2

plugins:
    - ./vendor/bref/bref

functions:
    report-api:
        handler: index.php
        description: ''
        runtime: php-82

# Exclude files from deployment
package:
    patterns:
        - '!node_modules/**'
        - '!tests/**'
